# Publish GitHub workflow for Creating VM on Rack server
name: Publish GitHub workflow for Creating VM on Rack server

on:
  push:
    branches: [ master ]

jobs:
       
  build:
    runs-on: self-hosted
    steps:
#      - uses: actions/checkout@2
      - name: Step 1 - Build Cloud Image
        run: sh ./bootstart_new_vm.sh
