# This is a basic workflow to help you get started with Actions

name: Create New VM on HOST machine at openshift.truetech.solutions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Time of starting Building Cloud Image
      - name: Starting to run steps
        run:  echo "Started - `date`"

        # Building cloud Image
      - name: Build Cloud Image
        run: sh ./bootstart_new_vm.sh

        # Building cloud Image
      - name: Deploying New ubuntu18 VM
        run: sh ./virsh.sh

        # Listing VM's
      - name: Deploying New ubuntu18 VM
        run: sh ./listing_all_vms    

       # Time of Completion Building Cloud Image
      - name: Ending executing steps.
        run: |
          echo "Completed - `date`"
          echo "Image saved on Host VM"
